# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posts',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
